21/12/06

git push 시 error 발생
fatal: cannot lock ref 'HEAD': unable to resolve 
reference 'refs/heads/master': reference broken

이유 : 데이터 유실 등의 문제 있는 부분이 있어 git에서 막는 것

해결 : git push origin +master
 에러와 상관없이 강제로 push


 21/12/30

 git add 시 error 발생
 warning: LF will be replaced by CRLF in zoom/package-lock.json.
The file will have its original line endings in your working directory        
warning: LF will be replaced by CRLF in zoom/package.json.
The file will have its original line endings in your working directory 

이유 : 마지막 줄

해결 : git config (--global) core.autocrlf true

 22/01/22

 git commit 시 error 발생
 fatal: cannot lock ref 'HEAD': unable to 
resolve reference 'refs/heads/master': reference broken

 이유 : branch 이름??

 해결 : git rm .git/refs/heads/master
        git fetch
        git push origin +master

error: update_ref failed for ref 'refs/remotes/origin/master': 
cannot lock ref 'refs/remotes/origin/master': 
unable to resolve reference 'refs/remotes/origin/master': 
reference broken

 이유 : ???

 해결 : push가 되긴 됨

 해결 2 : defalt branch를 master에서 main으로 바꿈. error 안 남.
          github contribution(잔디밭) 삭제됨


 22/02/10

 error : fatal: cannot lock ref 'HEAD': 
 unable to resolve reference 
 'refs/heads/main': reference broken

  이유 : ???? 왜 또

  과정 :
  git rm .git/refs/heads/main
  fatal: pathspec '.git/refs/heads/main' did not match any files

  폴더 경로 .git/refs/heads/branch 폴더에서 main 파일 삭제

  git pull 함.
  fatal: bad object refs/remotes/origin/main
  error: https://github.com/glitter1221/clone did not send all 
  necessary objects

  git fetch 함.
  fatal: bad object refs/remotes/origin/main
  error: https://github.com/glitter1221/clone did not send all 
  necessary objects

  git add commit push, push에서 error 발생
  error: failed to push some refs to 'https://github.com/glitter1221/clone'
  hint: Updates were rejected because the tip of your current branch is behind
  hint: its remote counterpart. Integrate the remote changes (e.g.
  hint: 'git pull ...') before pushing again.
  hint: See the 'Note about fast-forwards' in 'git push --help' for details.

  git push origin +main 함.
  + fced09e...ed56055 main -> main (forced update)
  error: update_ref failed for ref 'refs/remotes/origin/main': 
  cannot lock ref 'refs/remotes/origin/main': unable to resolve reference 'refs/remotes/origin/main': reference broken
  : push는 됐지만 reference는 여전히 broken

  rm .git/refs/remotes/origin 함.
  -> origin 폴더에 HEAD, master, main 파일 존재.

  git fetch함.

  push까지 매우 잘됨.

  원인 : 폴더에 이전 branch와 지금 branch 끼리 부딪힌 것 같음


  22/04/13

error: update_ref failed for ref 'refs/remotes/origin/main': 
cannot lock ref 'refs/remotes/origin/main': 
unable to resolve reference 'refs/remotes/origin/main': 
reference broken Everything up-to-date

원인 : ?

해결 : git add * -> commit -> push

error: update_ref failed for ref 'refs/remotes/origin/main': 
cannot lock ref 'refs/remotes/origin/main': 
unable to resolve reference 'refs/remotes/origin/main': 

원인 : ?

해결 : rm .git/refs/remotes/origin/main
    ->  * [new branch]      main       -> origin/main
     add commit 
    -> On branch main 
     push
    -> Everything up-to-date
    (github push 됨)

    Everything up-to-date가 나오는 이유 :
    이는 원격 저장소 상에 아직 master 브랜치가 작성되지 않았기 때문입니다. 
    push 할 때의 인수가 생략된 경우 기본적으로 원격 저장소와 로컬 저장소 
    양쪽에 모두 존재하는 브랜치가 push의 대상이 됩니다. 
    따라서 원격 저장소에 존재하지 않는 브랜치를 push하는 경우에는 
    저장소와 브랜치를 명시적으로 지정할 필요가 있습니다.


22/04/21

error: update_ref failed for ref 'refs/remotes/origin/main': 
cannot lock ref 'refs/remotes/origin/main': 
unable to resolve reference 'refs/remotes/origin/main': 
reference broken

원인 : ??

해결 : 일단 push는 잘 됨 그냥.